import {
  Container,
  Heading,
  Link,
  ListItem,
  Tag,
  Text,
  UnorderedList
} from "@chakra-ui/react";

export const metadata = {
  title: "Cookie Policy | Bessa | An LGBTQ Social Media App"
};

export default function Cookies() {
  return (
    <Container maxW={"container.lg"} py={16}>
      <Heading as={"h1"} mb={4}>
        Cookie Policy
      </Heading>
      <Tag mb={4}>Updated November, 21st, 2023</Tag>
      <Heading mb={4}>Definitions and key terms</Heading>
      <Text mb={4}>
        To help explain things as clearly as possible in this Cookie Policy,
        every time any of these terms are referenced, are strictly defined as:
      </Text>
      <UnorderedList mb={4}>
        <ListItem>
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </ListItem>
        <ListItem>
          Company: when this policy mentions “Company,” “we,” “us,” or “our,” it
          refers to Bessa, that is responsible for your information under this
          Cookie Policy.
        </ListItem>
        <ListItem>
          Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit Bessa and use
          the services.
        </ListItem>
        <ListItem>
          Personal Data: any information that directly, indirectly, or in
          connection with other information — including a personal
          identification number — allows for the identification or
          identifiability of a natural person.
        </ListItem>
        <ListItem>
          Service: refers to the service provided by Bessa as described in the
          relative terms (if available) and on this platform.
        </ListItem>
        <ListItem>
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
        </ListItem>
        <ListItem>Website: site, which can be accessed via this URL:</ListItem>
      </UnorderedList>
      <Heading mb={4}>Introduction</Heading>
      <Text mb={4}>
        This Cookie Policy explains how Bessa and its affiliates (collectively
        &quot;Bessa&quot;, &quot;we&quot;, &quot;us&quot;, and
        &quot;ours&quot;), use cookies and similar technologies to recognize you
        when you visit our app, including without limitation and any related
        URLs, mobile or localized versions and related domains / sub-domains
        (&quot;Websites&quot;). It explains what these technologies are and why
        we use them, as well as the choices for how to control them.
      </Text>
      <Heading mb={4}>What is a cookie?</Heading>
      <Text mb={4}>
        A cookie is a small text file that is stored on your computer or other
        internet connected device in order to identify your browser, provide
        analytics, remember information about you such as your language
        preference or login information. They&apos;re completely safe and
        can&apos;t be used to run programs or deliver viruses to your device.
      </Text>
      <Heading mb={4}>Why do we use cookies?</Heading>
      <Text mb={4}>
        We use first party and/or third party cookies on our app for various
        purposes such as:
      </Text>
      <UnorderedList mb={4}>
        <ListItem>
          To facilitate the operation and functionality of our app;
        </ListItem>
        <ListItem>
          To improve your experience of our app and make navigating around them
          quicker and easier;
        </ListItem>
        <ListItem>
          To allow us to make a bespoke user experience for you and for us to
          understand what is useful or of interest to you;
        </ListItem>
        <ListItem>
          To analyze how our app is used and how best we can customize it;
        </ListItem>
        <ListItem>
          To identify future prospects and personalize marketing and sales
          interactions with it;
        </ListItem>
        <ListItem>
          To facilitate the tailoring of online advertising to your interests.
        </ListItem>
        <ListItem>
          You: a person or entity that is registered with Bessa to use the
          Services.
        </ListItem>
      </UnorderedList>
      <Heading mb={4}>What type of cookies does Bessa use?</Heading>
      <Text mb={4}>
        Cookies can either be session cookies or persistent cookies. A session
        cookie expires automatically when you close your browser. A persistent
        cookie will remain until it expires or you delete your cookies.
        Expiration dates are set in the cookies themselves; some may expire
        after a few minutes while others may expire after multiple years.
        Cookies placed by the website you’re visiting are called “first party
        cookies”.
      </Text>
      <Text mb={4}>
        Strictly Necessary cookies are necessary for our app to function and
        cannot be switched off in our systems. They are essential in order to
        enable you to navigate around the app and use its features. If you
        remove or disable these cookies, we cannot guarantee that you will be
        able to use our app.
      </Text>
      <Text mb={4}>We use the following types of cookies in our app:</Text>
      <Heading mb={4}>Essential Cookies</Heading>
      <Text mb={4}>
        We use essential cookies to make our app work. These cookies are
        strictly necessary to enable core functionality such as security,
        network management, your cookie preferences and accessibility. Without
        them you wouldn&apos;t be able to use basic services. You may disable
        these by changing your browser settings, but this may affect how the
        Websites function.
      </Text>
      <Heading mb={4}>Performance and Functionality Cookies</Heading>
      <Text mb={4}>
        These cookies are used to enhance the performance and functionality of
        our app but are non-essential to their use. However, without these
        cookies, certain functionality like videos may become unavailable or you
        would be required to enter your login details every time you visit the
        app as we would not be able to remember that you had logged in
        previously.
      </Text>
      <Heading mb={4}>Marketing Cookies</Heading>
      <Text mb={4}>
        These account-based marketing cookies enable us to identify future
        prospects and personalize sales and marketing interactions with them.
      </Text>
      <Heading mb={4}>Analytics and Customization Cookies</Heading>
      <Text mb={4}>
        These cookies collect information that is used to help us understand how
        our app is being used or how effective our marketing campaigns are, or
        to help us customize our app for you.
      </Text>
      <Text mb={4}>
        We use cookies served by Google Analytics to collect limited data
        directly from end-user browsers to enable us to better understand your
        use of our app. Further information on how Google collects and uses this
        data can be found at: https://www.google.com/policies/privacy/partners/.
        You can opt-out of all Google supported analytics on our Websites by
        visiting: https://tools.google.com/dlpage/gaoptout.
      </Text>
      <Heading mb={4}>Advertising Cookies</Heading>
      <Text mb={4}>
        These cookies collect information over time about your online activity
        on the app and other online services to make online advertisements more
        relevant and effective to you. This is known as interest-based
        advertising. They also perform functions like preventing the same ad
        from continuously reappearing and ensuring that ads are properly
        displayed for advertisers. Without cookies, it’s really hard for an
        advertiser to reach its audience, or to know how many ads were shown and
        how many clicks they received.
      </Text>
      <Heading mb={4}>Social Media Cookies</Heading>
      <Text mb={4}>
        These cookies are used when you share information using a social media
        sharing button or “like” button on our Site or you link your account or
        engage with our content on or through a social networking website such
        as Facebook, Twitter or Google+. The social network will record that you
        have done this. These cookies may also include certain code that has
        been placed on the platform to help track conversions from ads, optimize
        ads based on collected data, build targeted audiences for future ads,
        and remarket to qualified users who have already taken certain action on
        the platform.
      </Text>
      <Heading mb={4}>Third Party Cookies</Heading>
      <Text mb={4}>
        Some cookies that have been set on our app are not set on a first party
        basis by Bessa. The Websites can be embedded with content from third
        parties to serve advertising. These third party service providers may
        set their own cookies on your web browser. Third party service providers
        control many of the performance and functionality, advertising,
        marketing and analytics cookies described above. We do not control the
        use of these third party cookies as cookies can only be accessed by the
        third party that originally set them.
      </Text>
      <Heading mb={4}>How you can manage cookies?</Heading>
      <Text mb={4}>
        Most browsers allow you to control cookies through their
        &apos;settings&apos; preferences. However, if you limit the ability of
        websites to set cookies, you may worsen your overall user experience,
        since it will no longer be personalized to you. It may also stop you
        from saving customized settings like login information. Browser
        manufacturers provide help pages relating to cookie management in their
        products.
      </Text>
      <Text mb={4}>
        Browser manufacturers provide help pages relating to cookie management
        in their products. Please see below for more information.
      </Text>
      <UnorderedList mb={4}>
        <ListItem>Google Chrome</ListItem>
        <ListItem>Internet Explorer</ListItem>
        <ListItem>Mozilla Firefox</ListItem>
        <ListItem>Safari (Desktop)</ListItem>
        <ListItem>Safari (Mobile)</ListItem>
        <ListItem>Android Browser</ListItem>
        <ListItem>Opera</ListItem>
        <ListItem>Opera Mobile</ListItem>
      </UnorderedList>

      <Heading mb={4}>
        Blocking and disabling cookies and similar technologies
      </Heading>
      <Text mb={4}>
        Wherever you&apos;re located you may also set your browser to block
        cookies and similar technologies, but this action may block our
        essential cookies and prevent our website from functioning properly, and
        you may not be able to fully utilize all of its features and services.
        You should also be aware that you may also lose some saved information
        (e.g. saved login details, site preferences) if you block cookies on
        your browser. Different browsers make different controls available to
        you. Disabling a cookie or category of cookie does not delete the cookie
        from your browser, you will need to do this yourself from within your
        browser, you should visit your browser&apos;s help menu for more
        information.
      </Text>
      <Heading mb={4}>Changes To Our Cookie Policy</Heading>
      <Text mb={4}>
        We may change our Service and policies, and we may need to make changes
        to this Cookie Policy so that they accurately reflect our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Cookie
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Cookie Policy. If you do not want to agree to this or any
        updated Cookie Policy, you can delete your account.
      </Text>
      <Heading mb={4}>Your Consent</Heading>
      <Text mb={4}>
        By using our app, registering an account, or making a purchase, you
        hereby consent to our Cookie Policy and agree to its terms.
      </Text>
      <Heading mb={4}>Contact Us</Heading>
      <Text>
        Have questions? Email{" "}
        <Text as={"b"}>
          <Link href={"mailto:topher@getbessa.com"}>topher@getbessa.com</Link>
        </Text>
      </Text>
    </Container>
  );
}
